language: node_js
node_js:
- node
services:
- docker
addons:
  sonarcloud:
    organization: timoa-github
before_script:
- cp src/examples/apps.json config/apps.json
- cp src/examples/config.json config/config.json
- npm run test:coverage
- bash scripts/sonar_scanner.sh
script:
- docker build -t timoa/app-stores-prometheus-exporter .
- docker-compose up -d
- docker ps -a
after_script:
- docker-compose down
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always