language: node_js
node_js:
- node
services:
- docker
addons:
  sonarcloud:
    organization: timoa-github
before_script:
- docker build -t timoa/app-stores-prometheus-exporter .
- docker-compose up -d
- docker ps -a
script:
- bash scripts/sonar_scanner.sh
after_script:
- docker-compose down
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always